name: FlintSpleef
description: A technology demonstration for the Flint framework.
author: Max Roncacé
website: http://caseif.net/
version: 1.0.1
api-version: 1.13
main: net.caseif.flint.spleef.Main
depend: [Steel]

commands:
  fs:
    description: Base command for the plugin.
    usage: /fs [command]

permissions:
  flintspleef.*:
    description: Grants full control of the plugin.
    default: op
    children:
      flintspleef.arena.*: true
      flintspleef.play: true
      flintspleef.lobby.*: true
  flintspleef.arena.*:
    description: Grants full control of arenas.
    default: op
    children:
      flintspleef.arena.create: true
      flintspleef.arena.remove: true
  flintspleef.arena.create:
    description: Grants permission to create arenas.
    default: op
  flintspleef.arena.remove:
    description: Grants permission to destroy arenas.
    default: op
  flintspleef.play:
    description: Grants permission to play FlintSpleef.
    default: true
  flintspleef.lobby.*:
    description: Grants all lobby sign permissions.
    default: op
    children:
      flintspleef.lobby.create: true
      flintspleef.lobby.destroy: true
  flintspleef.lobby.create:
    description: Grants permission to create lobby signs.
    default: op
  flintspleef.lobby.destroy:
    description: Grants permissiont o destroy lobby signs.
    default: op
