name: FlintSpleef
description: A technology demonstration for the Flint framework.
author: Max Roncacé
website: http://caseif.net/
version: 1.0.0-SNAPSHOT
main: net.caseif.flint.spleef.Main
depend: [Steel]

commands:
  fs:
    description: Base command for the plugin.
    usage: /fs [command]

permissions:
  fs.*:
    description: Grants full control of the plugin.
    default: op
    children:
      fs.arena.*: true
      fs.play: true
  fs.arena.*:
    description: Grants full control of arenas.
    default: op
    children:
      fs.arena.create: true
      fs.arena.remove: true
  fs.arena.create:
    description: Grants permission to create arenas.
    default: op
  fs.arena.remove:
    description: Grants permission to destroy arenas.
    default: op
  fs.play:
    description: Grants permission to play FlintSpleef.
    default: true
